### ISSUE TITLE
Getting undefined method `file' for nil:NilClass in Carriwewave 2.1.1

### ISSUE THREAD

**Issue by JamesAnthonyPino** [carrierwaveuploader/carrierwave#2539]
I have an application that uses a mount_uploader like so:

`mount_uploader :cdn_upload, CdnUploader`

where CdnUploader is:

`class CdnUploader < CarrierWave::Uploader::Base`

When I updated Carrierwave from 2.10 to 2.1.1, the following error is observed

```
ImportError:
       An unexpected error occurred: undefined method `file' for nil:NilClass
```

It seems that the code is failing to open the file in a line similar to this:

```
self.mime_type = MimeMagic.by_magic(File.open(cdn_upload.file.file)).type
```
When inspecting `cdn_upload.file.file`, it is `nil`.

The CHANGELOG for version 2.1.1 does not seem to show any breaking changes.

**Comment by mshibuya** [comment]
Stale.
