### ISSUE TITLE
Carrierwave issue or Mongoid 2.1.2 issue?

### ISSUE THREAD

**Issue by tranngocsam** [carrierwaveuploader/carrierwave#416]
If I use carrierwave with mongoid 2.1.2, I got this error

```
NameError (undefined local variable or method `setup_modifications' for #<Image:0xcc3fb84>):
  activemodel (3.0.9) lib/active_model/attribute_methods.rb:392:in `method_missing'
  mongoid (2.1.2) lib/mongoid/attributes.rb:153:in `method_missing'
  carrierwave (0.5.6) lib/carrierwave/orm/mongoid.rb:42:in `urls='
  mongoid (2.1.2) lib/mongoid/attributes/processing.rb:97:in `process_attribute'
  mongoid (2.1.2) lib/mongoid/attributes/processing.rb:25:in `block in process'
  mongoid (2.1.2) lib/mongoid/attributes/processing.rb:23:in `each_pair'
  mongoid (2.1.2) lib/mongoid/attributes/processing.rb:23:in `process'
  mongoid (2.1.2) lib/mongoid/document.rb:130:in `block in initialize'
  mongoid (2.1.2) lib/mongoid/relations/builders.rb:47:in `building'
  mongoid (2.1.2) lib/mongoid/document.rb:127:in `initialize'
  app/controllers/images_controller.rb:37:in `new'
```

Line 37 of images_controller.rb:

``` ruby
@image = Image.new(params[:image])
```

It works fine with mongoid 2.0.2
