### ISSUE TITLE
ssrf_filter '1.1.0' introducing a breaking change

### ISSUE THREAD

**Issue by ovidiuanca** [carrierwaveuploader/carrierwave#2625]
Since `ssrf_filter` updated its [version](https://github.com/arkadiyt/ssrf_filter/pull/51/files) from `1.0.8` to `1.1.0`, there is an error being raised:

```
def filename_from_uri
  CGI.unescape(File.basename(uri.path))
end

# bash
undefined method `path' for nil:NilClass

CGI.unescape(File.basename(uri.path))

```

To give more information, the `uri` object above is constructed within the following code snippet:

```
response = SsrfFilter.get(uri, headers: headers) do |req|
  request = req
end
response.uri = request.uri
```

`request.uri` now comes as `nil` from the `SsrfFilter.get` method.

I am not sure whether this issue belongs in here, or if it should be posted to `ssrf_filter`.

**Comment by courtsimas** [comment]
👀

**Comment by github-vinova** [comment]
i got an error too. It's working when i downgrade version from 1.1.1 to 1.0.8.

<img width="1432" alt="Screen Shot 2022-09-08 at 10 25 19" src="https://user-images.githubusercontent.com/108251356/189056954-debf9e5e-c6b6-4887-aa1d-819e00364ade.png">

**Comment by dboiii** [comment]
I got an error too. It's working when downgrade version 1.1.1 to 1.0.8

<img width="1432" alt="Screen Shot 2022-09-08 at 10 25 19" src="https://user-images.githubusercontent.com/4137588/189057730-42da6c17-ef2c-408f-8f42-9a8853dfe019.png">

**Comment by vadim-zverugo** [comment]
I faced with this issue too after upgrading the `ssrf_filter` from v1.0 to v1.1. Fortunetely, it was caught by the tests and I fixed them by adding `Content-Disposition: 'attachment; filename="sample.png"' HTTP header to the testing requests. 

But another more critical issue brought up. When trying to upload a file using the remote URL (e.g. `model.remote_{field}_url=`) the following error ocurrs: `NoMethodError: undefined method `closed?' for nil:NilClass`

I didn't have a time for debugging so just downgraded the `ssrf_filter` lib back to v1.0.x

**Comment by BrianHawley** [comment]
I patched the `request_proc` issue and it had the same `stream_check` error.

The problem is that `SsrfFilter.get` returns the response before reading the body, then closes the connection. RemoteFile then attempts to read the body after the connection is closed. The solution would be, at least when using ssrf_filter 1.1.x, to use this code:
```ruby
response = SsrfFilter.get(uri, headers: headers, request_proc: ->(req) { request = req }, &:body)
```

I'll adjust my PR accordingly.

**Comment by guillec** [comment]
This was also causing issues for me while testing downloading remote files. 
I was stubbing the response to fetching a remote file and uri.path was throwing error since uri was nil.

Downgrading to 1.0.8 fixed the issue for me.
