### ISSUE TITLE
Error: 'wrong number of arguments (given 2, expected 1)' for remote_image_url

### ISSUE THREAD

**Issue by oleg-voloshyn** [carrierwaveuploader/carrierwave#2103]
Hi all.
after update Rails from `4.2` to `5.0.1` doesn't work `remote_image_url`

my technologies:
`rails 5.0.1`
`carrierwave 1.0.0`
`carrierwave-base64 2.3.4`
 `cloudinary 1.3.0`

In model
```
class User < ApplicationRecord
   mount_base64_uploader :avatar, AvatarUploader
end
```

when I try create new user with avatar in rails console ([example from docs](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Upload-remote-image-urls-to-your-seedfile))
```
User.create(name: 'John', remote_avatar_url: 'https://pbs.twimg.com/profile_images/1980294624/DJT_Headshot_V2.jpg', ....)
```

I get error `wrong number of arguments (given 2, expected 1)`
this example worked with rails `4.2`

Do you have any ideas what's wrong? Thanks a lot.

**Comment by oleg-voloshyn** [comment]
I made rollback `carrierwave` version from `1.0.0` to `0.11.2` and now it works for me

**Comment by arpancj** [comment]
I am getting the same error with the v 1.0. Rolling back to 0.11.2 worked.

**Comment by ahmadabdul3** [comment]
You guys probably have the wrong version of Cloudinary::Carrierwave, currently rubygems.org is set to 1.4 but the gem has been updated to 1.5, point your gem to the git repo and you'll get the latest version and this should work with carrierwave v 1.0

**Comment by josue** [comment]
@ahmadabdul3  Thanks for suggestion, the issue is gone now. I updated my Gemfile to:

```ruby
gem 'carrierwave', :git => 'https://github.com/carrierwaveuploader/carrierwave.git', :branch => 'master'
gem 'cloudinary', :git => 'https://github.com/cloudinary/cloudinary_gem.git', :branch => 'master'
```

**Comment by zivkovicj** [comment]
I tried to fix this issue by using CarrierWave version 0.11.2. But now I get:

undefined method `fog_provider=' for CarrierWave::Uploader::Base:Class (NoMethodError)

The offending line of code is in my /config/initializers/carrierwave.rb file that I setup in order to get carrierwave cooperating with aws so that I can use it with heroku.
