### ISSUE TITLE
Regression in carrierwave 1.3.0: NameError

### ISSUE THREAD

**Issue by jaredbeck** [carrierwaveuploader/carrierwave#2363]
The following works in 1.2.3, and raises a NameError in 1.3.0:

```ruby
# app/models/redacted.rb
class Redacted
  mount_uploader :cw_redacted_file, ::RedactedUploader
end

# app/views/admin/redacted/index.html.haml, lines 85-86
- unless redacted.cw_redacted_file.file.nil? # line 85
  = link_to 'Redacted', redacted.cw_redacted_file.url # line 86
```

```
NameError in Admin::Redacted#index
Showing app/views/admin/redacted/index.html.haml 
where line #86 raised:
undefined method `url' for class `NilClass'
Did you mean?  URI
```

Why would `cw_redacted_file` work on line 85 and then not work on line 86? Weird.

**Comment by mshibuya** [comment]
Sounds like duplicate of #2361, try with the latest 1.3.1 release.
