### ISSUE TITLE
MiniMagick >= 4.x has breaking changes

### ISSUE THREAD

**Issue by astjohn** [carrierwaveuploader/carrierwave#1520]
A quick glance at the change log and I can see a few breaking changes for the 4.x release.
https://github.com/minimagick/minimagick/releases

I can confirm that nothing was working as intended with minimagic 4.0.1. I am using mongoid-carrierwave, rails4 and mongoid4. 

Result was either a silent failure or `CarrierWave::ProcessingError: Failed to manipulate with MiniMagick`.

It might be best to lock minimagick dependency at 3.8.1 or look into the breaking changes.
Cheers!

**Comment by doxxon** [comment]
+1

**Comment by pencilcheck** [comment]
+1

**Comment by stgeneral** [comment]
Seems I had a chance to have CarrierWave to work with every version MiniMagick (4.0.1, 4.0.2, 4.0.3, 4.0.4) without any problems. Now it work for me on version MiniMagick 4.1. Operations: re-sizing only.

**Comment by aried3r** [comment]
OS X 10.10.2
Ruby 2.2.0
Rails 4.2.0
mini_magick 4.1.0
carrierwave 0.10.0
imagemagick: 6.9.0-9

Just as @stgeneral, I did not run into any problems. Operations: resize only.

**Comment by batamire** [comment]
+1

I was getting "undefined method `gravity' for #<MiniMagick::Tool::Mogrify...", (only in production, dev is fine on mac os 10.10.2) downgraded to 3.8.1 so it works now. Operation: resize_to_fill.

CentOS 5.11
Ruby 2.2.0
mini_magick 4.1.1
carrierwave 0.10.0
imagemagick: 6.9.0-10

**Comment by NARKOZ** [comment]
`resize_to_fill` process raises exception `undefined method gravity' for #<MiniMagick::Tool::Mogrify:>` when mini_magick uses GraphicsMagick processor.

**Comment by tomprats** [comment]
I'm getting the same error as @NARKOZ, would love to be able to use GraphicsMagick. Right now it looks good if I use `resize_to_fit` instead, but that's obviously not quite what I want to do. Hope this gets fixed soon!

**Comment by tomprats** [comment]
This issue appears to be related https://github.com/minimagick/minimagick/issues/264

**Comment by jonathanng** [comment]
This issue is also related to #1629.

Can't use the push method.

**Comment by tonytonyjan** [comment]
+1, same as @NARKOZ encountered.

**Comment by kreintjes** [comment]
I am experiencing the same problem as in issue #1629

**Comment by felixbuenemann** [comment]
The issue @NARKOZ mentioned has been fixed in mini_magick 4.2.10, see minimagick/minimagick#264 for the discussion.

**Comment by thomasfedb** [comment]
If there is a still an issue with MiniMagick compat. please open a new issue.
