### ISSUE TITLE
Test failure after upgrading from 1.2.3 to 1.3.0

### ISSUE THREAD

**Issue by tbr00** [carrierwaveuploader/carrierwave#2361]
After upgrading from 1.2.3 to 1.3.0 I have failing tests.  The problem is when rendering a form which attempts to display the filename of an uploaded file.   I get the error:

ActionView::Template::Error:         ActionView::Template::Error: undefined method `url' for class `NilClass'

reported on the code:
      <%= a.object.filename.to_s.split('/').last %><br>

As I have no 'url' method I turned on a full trace and find the error actually comes from line 502 in fog.rb in:

        def url_options_supported?(local_file)
          parameters = file.method(:url).parameters
          parameters.count == 2 && parameters[1].include?(:options)
        end

While I don't begin to understand what may be going on, this code does not seem to be in version 1.2.3 and it looks suspicious that the parameter 'local_file' is not actually used.  Indeed blindly changing the code to:

parameters = local_file.method(:url).parameters

results in the test passing.
Perhaps someone who does understand could comment?

**Comment by mshibuya** [comment]
Thanks for reporting, pushed a fix as https://github.com/carrierwaveuploader/carrierwave/commit/0b9a64a1bb9f20d1de154dc3bf2e2dd988210220.
