### ISSUE TITLE
AR cucumber features fails on rails >= 3.1.1 (works on 3.1.0)

### ISSUE THREAD

**Issue by slbug** [carrierwaveuploader/carrierwave#535]
```
(::) failed steps (::)

NoMethodError: undefined method `error' for nil:NilClass: INSERT INTO "users" ("avatar") VALUES (?) (ActiveRecord::StatementInvalid)
./features/step_definitions/activerecord_steps.rb:13:in `/^I save the active record$/'
features/mount_activerecord.feature:27:in `And I save the active record'

NoMethodError: undefined method `error' for nil:NilClass: INSERT INTO "users" ("avatar") VALUES (?) (ActiveRecord::StatementInvalid)
./features/step_definitions/activerecord_steps.rb:13:in `/^I save the active record$/'
features/mount_activerecord.feature:35:in `And I save the active record'

NoMethodError: undefined method `error' for nil:NilClass: INSERT INTO "users" ("avatar") VALUES (?) (ActiveRecord::StatementInvalid)
./features/step_definitions/activerecord_steps.rb:13:in `/^I save the active record$/'
features/mount_activerecord.feature:43:in `And I save the active record'

Failing Scenarios:
cucumber features/mount_activerecord.feature:24
cucumber features/mount_activerecord.feature:32
cucumber features/mount_activerecord.feature:40
```

full trace - https://gist.github.com/1383302
