### ISSUE TITLE
Fog AWS doesn't work with 0.11.0

### ISSUE THREAD

**Issue by vadim-zverugo** [carrierwaveuploader/carrierwave#1914]
Ruby 2.2.2p95
RoR 4.2.6

`Gemfile`
```
gem 'carrierwave', '0.11.0'
gem 'fog-aws', '0.9.2'
``` 

`config/initializers/carrierwave.rb`
```
CarrierWave.configure do |config|
  if Rails.env.test?
    config.storage = :file
  else
    config.fog_provider = 'fog/aws'
    config.fog_credentials = {
      provider: 'AWS',
      aws_access_key_id: Rails.application.secrets.aws_access_key_id,
      aws_secret_access_key: Rails.application.secrets.aws_secret_access_key,
      region: Rails.application.secrets.s3_region
    }
    config.fog_directory = Rails.application.secrets.s3_bucket
    config.fog_attributes = {
      'Cache-Control' => "max-age=#{365.days.to_i}"
    }
    config.cache_dir = "#{::Rails.root}/tmp/uploads"
  end
end
```

`app/uploaders/image_uploader.rb`
```
class ImageUploader < CarrierWave::Uploader::Base
  storage :fog
  ...
end
```

The error I see when running my app:
```
/Users/vadimzverugo/Projects/personal/avservice/config/initializers/carrierwave.rb:5:in `block in <top (required)>': undefined method `fog_provider=' for CarrierWave::Uploader::Base:Class (NoMethodError)
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/carrierwave-0.11.0/lib/carrierwave/uploader/configuration.rb:118:in `configure'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/carrierwave-0.11.0/lib/carrierwave.rb:14:in `configure'
	from /Users/vadimzverugo/Projects/personal/avservice/config/initializers/carrierwave.rb:1:in `<top (required)>'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:268:in `load'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/engine.rb:652:in `block in load_config_initializer'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/notifications.rb:166:in `instrument'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/engine.rb:651:in `load_config_initializer'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/engine.rb:615:in `each'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/engine.rb:615:in `block in <class:Engine>'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/initializable.rb:30:in `run'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:420:in `block (2 levels) in each_strongly_connected_component_from'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:419:in `block in each_strongly_connected_component_from'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `each'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/initializable.rb:44:in `tsort_each_child'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `call'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:413:in `each_strongly_connected_component_from'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
	from /Users/vadimzverugo/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/application.rb:352:in `initialize!'
	from /Users/vadimzverugo/Projects/personal/avservice/config/environment.rb:5:in `<top (required)>'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/activesupport-4.2.6/lib/active_support/dependencies.rb:274:in `require'
	from /Users/vadimzverugo/Projects/personal/avservice/config.ru:3:in `block in <main>'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:55:in `initialize'
	from /Users/vadimzverugo/Projects/personal/avservice/config.ru:in `new'
	from /Users/vadimzverugo/Projects/personal/avservice/config.ru:in `<main>'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:49:in `eval'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/builder.rb:40:in `parse_file'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:299:in `build_app_and_options_from_config'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:208:in `app'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/server.rb:61:in `app'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/rack-1.6.4/lib/rack/server.rb:336:in `wrapped_app'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/server.rb:78:in `start'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/vadimzverugo/.rvm/gems/ruby-2.2.2/gems/railties-4.2.6/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/vadimzverugo/Projects/personal/avservice/bin/rails:4:in `require'
	from /Users/vadimzverugo/Projects/personal/avservice/bin/rails:4:in `<top (required)>'
	from -e:1:in `load'
	from -e:1:in `<main>'
```

**Comment by oboxodo** [comment]
I upgraded from 0.10 to 0.11 because I wanted to leverage the possibility to only require `fog-aws` instead of the full `fog` package which loads a ton of unneeded gems. But it failed with the same error mentioned by @vadim-zverugo.

Further investigation shows that the newly released 0.11 version gem is missing A LOT of commits from master, including the patches to support `fog-aws` which have been sitting in `master` for months (years?).

I'd like to contribute by backporting that to the 0.11-stable branch, but I can't fully understand how this repo's branches are organized. It seems to me that `master` has deviated a lot from the stable branches and these branches have nothing to do with `master` since long ago.

Any clarification is appreciated.

**Comment by javierjulio** [comment]
Having same issue. Noticing the 0.11-stable branch is missing some important changes. The fog_provider isn't set https://github.com/carrierwaveuploader/carrierwave/blob/0.11-stable/lib/carrierwave/uploader/configuration.rb but it does exist in same version of file on master. Are we even sure what commits are in the 0.11 release?

**Comment by eloyesp** [comment]
A workaround for this is adding an empty file `lib/fog.rb` and manually requiring 'carrierwave/storage/fog' in the initializer. (It is working for `v0.10.0` but should also work for `v0.11.0`).

**Comment by jbschrades** [comment]
Even if I rollback to `0.10.0` I'm still having issues with fog and AWS.

```
ArgumentError:  is not a recognized provider
from /usr/local/rvm/gems/ruby-2.3.0/gems/fog-core-1.37.0/lib/fog/core/services_mixin.rb:12:in `new'
```

This is the case whether I use `fog` or `fog-aws`

I'm assuming this is the same issue?

**Comment by oboxodo** [comment]
@eloyesp that sounds like a simple and not very intrusive hack. But I'm not sure I follow what you mean. Could you explain a bit further? Maybe some sample code?

You mention `lib/fog.rb` being empty, but then also mention "manually requiring `carrierwave/storage/fog`". Where would you do that? I think the important bit would be where to require `fog-aws` instead of `fog`, right?

Thank you very much for your pointer, though.

**Comment by eloyesp** [comment]
@oboxodo I've required `carrierwave/storage/fog` in the carrierwave initializer and you don't need to require 'fog-aws' as bundler is already doing that for you (you can also do it in the initializer if you want).

@jbschrades It seems like another issue, it seems that you are not setting a credential:

```ruby
    config.fog_credentials = {
      provider: 'AWS', # <----- this line seems to be the issue.
      aws_access_key_id: Rails.application.secrets.aws_access_key_id,
      aws_secret_access_key: Rails.application.secrets.aws_secret_access_key,
      region: Rails.application.secrets.s3_region
    }
```

**Comment by jbschrades** [comment]
@eloyesp thanks for the response.  My problem was that I had double-quotes on that line like `"AWS"` instead of single like `'AWS'`.  I've used this config is many apps, so I was vexed.  Didn't realize the double-quotes would be a problem.

Sorry for this being off topic.

**Comment by oboxodo** [comment]
@eloyesp thanks! That did the trick. So simple...

**Comment by vadim-zverugo** [comment]
Thanks @eloyesp, but I'd like to see `fog-aws` working without hacks, especially if it's annotated in the changelog for v.0.11.0. Maybe we can hear some updates from Carrierwave authors about v0.11.1?

**Comment by jaredbeck** [comment]
As Diego said, this feature (using only `fog-aws`) is in `master` and in the [docs][1]. The following works for me:

```ruby
# Gemfile
gem "carrierwave", github: "carrierwaveuploader/carrierwave"
gem "fog-aws"

# config/initializers/carrierwave.rb
CarrierWave.configure do |config|
  config.fog_provider = "fog/aws"
  config.fog_credentials = { provider: "AWS", # etc. }
end
```

Of course, disclaimer: use `master` at your own risk.

[1]: https://github.com/carrierwaveuploader/carrierwave#fog

**Comment by connorshea** [comment]
This is a pretty big deal, we need a 0.12.0 release if possible.

**Comment by jaredbeck** [comment]
> This is a pretty big deal, we need a 0.12.0 release if possible.

The next planned release was 1.0.0 (https://github.com/carrierwaveuploader/carrierwave/milestone/2), but unfortunately Thiago has not had time to work on this project lately (see https://github.com/carrierwaveuploader/carrierwave/issues/1987).

**Comment by mshibuya** [comment]
Please use 1.0.0.beta release or master branch to take advantage of fog-aws.

**Comment by jaredbeck** [comment]
> Please use 1.0.0.beta release or master branch to take advantage of fog-aws.

Thanks Mitsuhiro. I have updated to carrierwave 1.0.0.beta and fog-aws 0.12 and everything seems to be working fine. 

```
bundle | grep fog
Using fog-core 1.42.0
Using fog-json 1.0.2
Using fog-xml 0.1.2
Using fog-aws 0.12.0
```

Yay, no more unnecessary fogs!
